#!/usr/bin/env sh

basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/micro-suite/bin/micro-suite" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/micro-suite/bin/micro-suite" "$@"
  ret=$?
fi
exit $ret
